"""
calm.policy.policy_engine — Unified CALM V2 Policy Engine coordinating all signals and constraints.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Set
from calm.models.app_state import LifecycleState
from calm.models.prediction import PredictionResult
from calm.telemetry.collector import TelemetryCollector
from calm.telemetry.context import ContextExtractor
from calm.policy.priority import PriorityEngine
from calm.policy.pressure import PressureEngine, PressureLevel, PressureTrend
from calm.policy.hysteresis import HysteresisController
from calm.policy.burst import BurstDetector
from calm.utils.config import CALMConfig


@dataclass
class PolicyDecision:
    """Decision output generated by the CALM Policy Engine for a simulation tick."""
    foreground_item: str
    priority_scores: Dict[str, float]
    target_states: Dict[str, LifecycleState]
    pressure_level: PressureLevel
    pressure_trend: PressureTrend
    items_to_prewarm: List[str] = field(default_factory=list)
    items_to_compress: List[str] = field(default_factory=list)
    items_to_evict: List[str] = field(default_factory=list)
    prediction_confidence: float = 0.0


class CALMPolicyEngine:
    """
    Core Policy Engine for CALM V2.
    Integrates telemetry, prediction confidence, memory pressure trend, burst protection,
    and hysteresis constraints to produce optimal target lifecycle states.
    """

    def __init__(
        self,
        config: CALMConfig,
        priority_engine: Optional[PriorityEngine] = None,
        pressure_engine: Optional[PressureEngine] = None,
        hysteresis_controller: Optional[HysteresisController] = None,
        burst_detector: Optional[BurstDetector] = None,
    ):
        self.config = config
        self.priority_engine = priority_engine or PriorityEngine(config.priority_weights)
        self.pressure_engine = pressure_engine or PressureEngine(config.pressure)
        self.hysteresis = hysteresis_controller or HysteresisController(config.hysteresis)
        self.burst_detector = burst_detector or BurstDetector()

    def evaluate(
        self,
        all_items: List[str],
        current_states: Dict[str, LifecycleState],
        foreground_item: str,
        prediction_result: Optional[PredictionResult],
        telemetry_collector: TelemetryCollector,
        current_tick: int,
        context_extractor: ContextExtractor,
        context_importances: Optional[Dict[str, float]] = None,
        # Ablation parameters
        enable_prediction: bool = True,
        enable_burst: bool = True,
        enable_hysteresis: bool = True,
        enable_pressure_trend: bool = True,
        enable_compression: bool = True,
        enable_context: bool = True,
    ) -> PolicyDecision:
        """
        Evaluates system state and outputs comprehensive PolicyDecision.
        """
        # 1. Extract context signals
        recency = context_extractor.compute_recency_scores(telemetry_collector, current_tick)
        frequency = context_extractor.compute_frequency_scores(telemetry_collector)
        burst_scores = context_extractor.compute_burst_scores(telemetry_collector)

        # 2. Compute priority scores with confidence weighting and ablation switches
        priority_scores = self.priority_engine.compute_scores(
            all_items=all_items,
            foreground_item=foreground_item,
            prediction_result=prediction_result,
            recency_scores=recency,
            frequency_scores=frequency,
            burst_scores=burst_scores,
            context_importances=context_importances,
            enable_prediction=enable_prediction,
            enable_burst=enable_burst,
            enable_context=enable_context,
        )

        pressure_level = self.pressure_engine.level
        pressure_trend = self.pressure_engine.trend
        confidence = prediction_result.confidence if prediction_result else 0.0

        target_states: Dict[str, LifecycleState] = dict(current_states)
        items_to_prewarm: List[str] = []
        items_to_compress: List[str] = []
        items_to_evict: List[str] = []

        # 3. Handle Foreground: Always target ACTIVE
        target_states[foreground_item] = LifecycleState.ACTIVE

        # 4. Prediction-driven prewarming (confidence-gated)
        if enable_prediction and prediction_result and confidence >= self.config.prediction.confidence_threshold:
            # Prewarm top predicted candidate(s) if confidence is sufficient
            for candidate in prediction_result.top_k[:self.config.prediction.top_k]:
                item = candidate.item_id
                if item == foreground_item:
                    continue

                can_promote = (
                    self.hysteresis.can_promote(
                        item, current_states[item], priority_scores[item], is_foreground=False
                    ) if enable_hysteresis else True
                )

                if can_promote:
                    # If high confidence and low pressure -> CACHED, else COMPRESSED
                    if confidence >= self.config.prediction.high_confidence_threshold and pressure_level == PressureLevel.LOW:
                        target_states[item] = LifecycleState.CACHED
                        items_to_prewarm.append(item)
                    elif enable_compression and current_states[item] == LifecycleState.ARCHIVED:
                        target_states[item] = LifecycleState.COMPRESSED
                        items_to_prewarm.append(item)

        # 5. Proactive compression under HIGH pressure or RISING trend
        proactive_compress_trigger = (
            (pressure_level == PressureLevel.HIGH and (pressure_trend == PressureTrend.RISING or not enable_pressure_trend))
            or (enable_pressure_trend and pressure_level == PressureLevel.MODERATE and pressure_trend == PressureTrend.RISING)
        )

        if enable_compression and proactive_compress_trigger:
            for item in all_items:
                if item == foreground_item:
                    continue
                if current_states[item] == LifecycleState.CACHED:
                    t = telemetry_collector.get_or_create(item)
                    can_dem = (
                        self.hysteresis.can_demote(
                            item, current_states[item], t.ticks_in_state, priority_scores[item]
                        ) if enable_hysteresis else True
                    )
                    # Protect bursty items from proactive demotion
                    if enable_burst and self.burst_detector.is_bursting(t):
                        can_dem = False

                    if can_dem:
                        target_states[item] = LifecycleState.COMPRESSED
                        items_to_compress.append(item)

        return PolicyDecision(
            foreground_item=foreground_item,
            priority_scores=priority_scores,
            target_states=target_states,
            pressure_level=pressure_level,
            pressure_trend=pressure_trend,
            items_to_prewarm=items_to_prewarm,
            items_to_compress=items_to_compress,
            items_to_evict=items_to_evict,
            prediction_confidence=confidence,
        )
